name: codehub
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.0.4
  dartz: ^0.10.0
  dio: ^4.0.1
  flash: ^2.0.3
  flutter_hooks: ^0.18.0
  flutter_secure_storage: ^4.2.1
  hooks_riverpod: ^0.14.0+5
  freezed_annotation: ^0.14.2
  oauth2: ^2.0.0
  webview_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  freezed: ^0.14.2
  lint: ^1.7.2

flutter:
  uses-material-design: true
